4xx IS BAD, WE NEED TO FIX IT.

The following HTTP errors are generated by the load balancer. The load balancer sends the HTTP code to the client, saves the request to the access log, and increments the `HTTPCode_ELB_4XX_Count` or `HTTPCode_ELB_5XX_Count` metric.

###### Errors

- [HTTP 400: Bad request](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-400-issues)
- [HTTP 401: Unauthorized](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-401-issues)
- [HTTP 403: Forbidden](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-403-issues)
- [HTTP 405: Method not allowed](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-405-issues)
- [HTTP 408: Request timeout](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-408-issues)
- [HTTP 413: Payload too large](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-413-issues)
- [HTTP 414: URI too long](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-414-issues)
- [HTTP 460](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-460-issues)
- [HTTP 463](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-463-issues)
- [HTTP 464](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-464-issues)
- [HTTP 500: Internal server error](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-500-issues)
- [HTTP 501: Not implemented](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-501-issues)
- [HTTP 502: Bad gateway](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-502-issues)
- [HTTP 503: Service unavailable](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-503-issues)
- [HTTP 504: Gateway timeout](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-504-issues)
- [HTTP 505: Version not supported](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-505-issues)
- [HTTP 507: Insufficient Storage](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-507-issues)
- [HTTP 561: Unauthorized](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-561-issues)

### HTTP 400: Bad request

Possible causes:

- The client sent a malformed request that does not meet the HTTP specification.
    
- The request header exceeded 16 K per request line, 16 K per single header, or 64 K for the entire request header.
    
- The client closed the connection before sending the full request body.
    

### HTTP 401: Unauthorized

You configured a listener rule to authenticate users, but one of the following is true:

- You configured `OnUnauthenticatedRequest` to deny unauthenticated users or the IdP denied access.
    
- The size of the claims returned by the IdP exceeded the maximum size supported by the load balancer.
    
- A client submitted an HTTP/1.0 request without a host header, and the load balancer was unable to generate a redirect URL.
    
- The requested scope doesn't return an ID token.
    
- You don't complete the login process before the client login timeout expires. For more information see, [Client login timeout](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html#client-login-timeout).
    

### HTTP 403: Forbidden

You configured an AWS WAF web access control list (web ACL) to monitor requests to your Application Load Balancer and it blocked a request.

### HTTP 405: Method not allowed

The client used the TRACE method, which is not supported by Application Load Balancers.

### HTTP 408: Request timeout

The client did not send data before the idle timeout period expired. Sending a TCP keep-alive does not prevent this timeout. Send at least 1 byte of data before each idle timeout period elapses. Increase the length of the idle timeout period as needed.

### HTTP 413: Payload too large

Possible causes:

- The target is a Lambda function and the request body exceeds 1 MB.
    
- The request header exceeded 16 K per request line, 16 K per single header, or 64 K for the entire request header.
    

### HTTP 414: URI too long

The request URL or query string parameters are too large.

### HTTP 460

The load balancer received a request from a client, but the client closed the connection with the load balancer before the idle timeout period elapsed.

Check whether the client timeout period is greater than the idle timeout period for the load balancer. Ensure that your target provides a response to the client before the client timeout period elapses, or increase the client timeout period to match the load balancer idle timeout, if the client supports this.

### HTTP 463

The load balancer received an **X-Forwarded-For** request header with too many IP addresses. The upper limit for IP addresses is 30.

### HTTP 464

The load balancer received an incoming request protocol that is incompatible with the version config of the target group protocol.

Possible causes:

- The request protocol is an HTTP/1.1, while the target group protocol version is a gRPC or HTTP/2.
    
- The request protocol is a gRPC, while the target group protocol version is an HTTP/1.1.
    
- The request protocol is an HTTP/2 and the request is not POST, while target group protocol version is a gRPC.